### ISSUE TITLE
Uklanjanje sleep()

### ISSUE THREAD

**Issue by dusaan-m** [lazargugleta/KPobnovi-oglas#2]
Istrazi malo vise kako funkcionise WebDriverWait().until().

Koriscenjem time() je puka sreca da li ce ti se dobro pokrenuti program i da li ce se sve lepo izvrsiti. Ti si po osecaju stavio sleep na nekoliko sekundi npr 5 sekundi ako se nekim slucajem desi da se element pojavio tek nakon 6 sekundi tebi ce program da pukne.

Takodje ti svaki put cekas 5 sekundi cak iako se element pojavio iste sekunde.

Sa wait.until mozes da obezbedis da ti se program izvrsi kako treba cak iako ima nekih cudnih kasnjenja u ucitavanju elemenata. Takodje dobijas na vremenu jer ne moras uvek fiksno da cekas vec odmah izvrsavas instrukcije cim se element ucita.

**Comment by lazargugleta** [comment]
Nisam mogao da namestim wait funkcionalnost ni u kom obliku jer ima vise razlicitih pristupa u Seleniumu.

Ako imas vremena pusti PR 🙌🏽

**Comment by lazargugleta** [comment]
Addressed in https://github.com/lazargugleta/KPobnovi-oglas/pull/3
